# Linguagem utilizada.
language: python

# Versão que a aplicação suporta.
python:
  - "3.6.3"

install:
  - gem install --user travis
  
# Faz a instalação com Sudo, para ter privilégio de Super Usuário.
sudo: required

script:
  - echo "ok"
  
